pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                git branch: 'master', url: 'https://github.com/Cheesykung/final_sdtp.git'
            }
        }
        stage('Download Dependencies') {
            steps {
                dir("backend"){
                    sh 'yarn install'
                }
            }
        }
        // stage('Deploy') {
        //     steps {
        //         withCredentials([string(credentialsId: 'team2-backend-docker', variable: 'team2sshPass')]) {
        //             script {
        //                 def remote = [:]
        //                 remote.host = '159.65.12.177'
        //                 remote.name = 'team2-ssh'
        //                 remote.user = 'root'
        //                 remote.password = "${team2sshPass}"
        //                 remote.allowAnyHosts = true

        //                 sshCommand remote: remote, command: "git clone https://github.com/trabnm1313/SDTP.git"
        //                 sshCommand remote: remote, command: "docker-compose -f SDTP/dockerCompose.yml up -d"
        //                 sshCommand remote: remote, command: "rm -r SDTP"
        //             }
        //         }
        //     }
        // }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}